{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "graphprotocol-node.fullname" $ }}
              servicePort: graphql
    {{- end }}
{{- end }}
---
{{- if .Values.ingressAdmin.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-admin
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
  {{- with .Values.ingressAdmin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressAdmin.tls }}
  tls:
    {{- range .Values.ingressAdmin.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressAdmin.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "graphprotocol-node.fullname" $ }}
              servicePort: json-rpc
    {{- end }}
{{- end }}
---
{{- if .Values.ingressWebsocket.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-ws
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
  {{- with .Values.ingressWebsocket.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressWebsocket.tls }}
  tls:
    {{- range .Values.ingressWebsocket.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressWebsocket.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "graphprotocol-node.fullname" $ }}
              servicePort: graphql-ws
    {{- end }}
{{- end }}
---
{{- if .Values.ingressIpfs.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "ipfs.fullname" . }}-ipfs
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
  {{- with .Values.ingressIpfs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressIpfs.tls }}
  tls:
    {{- range .Values.ingressIpfs.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressIpfs.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: {{ include "ipfs.fullname" $ }}
              servicePort: 5001
    {{- end }}
{{- end }}
